# Generated by Django 4.2.23 on 2025-08-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_question_invitation_choice_attempt_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Declined'), (4, 'Expired')], default=1),
        ),
    ]
