# Generated by Django 4.2.23 on 2025-08-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
